# Generated by Django 4.1.2 on 2022-10-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="email",),
    ]
